Shared sequencer integration
FuelLabs/fuel-core pull request #1922
Opened 2024-05-30 17:01 UTC by Dentosal

## Checklist
- [ ] Breaking changes are clearly marked as such in the PR description and changelog
- [ ] New behavior is reflected in tests
- [ ] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [ ] I have reviewed the code myself
- [ ] I have created follow-up issues caused by this PR and linked them here

2024-11-27 22:18 UTC, xgreenx commented
@Dentosal Could you apply latest changes from the https://github.com/FuelLabs/fuel-core/pull/2451 and https://github.com/FuelLabs/fuel-core/pull/2452 please?=)

2024-12-13 00:51 UTC, xgreenx commented
@Dentosal Could you also include https://github.com/FuelLabs/fuel-core/pull/2495 into the PR, please?=)

2024-12-13 00:53 UTC, xgreenx commented
The `CosmosError` was removed because it was not used after https://github.com/FuelLabs/fuel-core/pull/2451/commits/8bf2a3e0ea5ce72d7e9e1c1eda92477c60bb7857 commit

2024-12-31 00:33 UTC, xgreenx submitted a review, later dismissed

2024-12-31 00:35 UTC, xgreenx approved these changes

2025-01-03 09:13 UTC, AurelienFT approved these changes
I already reviewed when it was a PR for 0.40.x version. Seems similar LGTM with a little question

2025-01-03 09:13 UTC, AurelienFT commented on ci_checks.sh
> +cargo nextest run --all-features --workspace &&
What's the rationale behind this change on this PR ?

2025-01-03 10:01 UTC, acerone85 commented on crates/services/shared-sequencer/src/lib.rs
> +    account_prefix: String,
nit: missing documentation for the fields. 
But in general I'd like to understand what's the account prefix?

2025-01-03 10:19 UTC, acerone85 commented on crates/services/shared-sequencer/src/http_api.rs
> +        pub order: String,
In general I'm a fan of the newtype pattern to give context about what a value represents. 
But in abserve of that, who is the owner (I guess either a Fuel or Ethereum address) and what is the order of a topic?

2025-01-03 10:23 UTC, acerone85 commented on crates/services/shared-sequencer/src/http_api.rs
> +        pub order: String,
nvm, I see that this struct is redefined later and you use these fields only for deserialization purposes. Closing

2025-01-03 11:03 UTC, acerone85 commented on crates/services/shared-sequencer/src/lib.rs
> +        let chain_id = http_api::chain_id(&endpoints.blockchain_rest_api)
this gets fetched from the shared sequencer node. Is this supposed to be the same as the fuel chain id? If not, maybe best to rename the field as `ss_chain_id` or similar to avoid ambiguity

2025-01-03 11:46 UTC, acerone85 commented on crates/services/shared-sequencer/src/service.rs
> +    async fn blobs(&mut self) -> anyhow::Result<Option<SSBlobs>> {
This function seems to be doing three things at once: setting the account metadata, setting the previous topic order (not sure what that is), and then taking ownership of the blobs. However, it is not clear to me how these three are related

2025-01-03 11:47 UTC, acerone85 commented on crates/services/shared-sequencer/src/service.rs
> +    async fn blobs(&mut self) -> anyhow::Result<Option<SSBlobs>> {
would it be possible/advisable to split this function in two?

2025-01-03 11:55 UTC, acerone85 commented on crates/services/shared-sequencer/src/service.rs
> +                if let Some(blobs) = blobs {
nit: 
```rust
              let Some(blobs) = blobs  else { TaskNextAction::Continue } 
```
seems to be slightly more readable

2025-01-03 12:00 UTC, acerone85 commented on crates/services/shared-sequencer/src/lib.rs
> +        // We want to estimate the transaction to know hat amount and fee to use.
```suggestion
        // We want to estimate the transaction to know what amount and fee to use.
```

2025-01-03 12:05 UTC, acerone85 commented on crates/fuel-core/src/service.rs
> +        }
not for this PR, but maybe it's better here to have an enum that lists all the expected services, with feature-specific variants, and then use `strum_enum::count` to retrieve the expected services.

2025-01-03 12:18 UTC, acerone85 commented
I have reviewed the whole code. 
My understanding is that the shared sequencer service keeps monitoring for new ImportedBlocks from the BlockImporter and posts the corresponding blobs to the sequencer node. 

From the architectural point of view I would like to understand the following (note that my questions probably spill into the shared sequencer domain): 
1. What's the high level architecture of the shared sequencer? I understand that nodes with shared sequencer integration enabled will connect  and post imported blocks to a ss node, and then these will be responsible to agree that they imported the same blocks using tendermint. But I'm trying connect dots and making assumptions here. Is my understanding correct? 
2. What is validated by the consensus layer? Is it just the block content? 
3. How is the result of the consensus used? In particular, I'd expect each tendermint iterations to produce a quorum certificate: how is it used? Is it posted to L1?

2025-01-03 12:18 UTC, acerone85 approved these changes

2025-01-03 13:50 UTC, Dentosal commented on ci_checks.sh
> +cargo nextest run --all-features --workspace &&
A mistake. Removed in b3ea6058e1.

2025-01-03 13:50 UTC, Dentosal commented on crates/services/shared-sequencer/src/lib.rs
> +        let chain_id = http_api::chain_id(&endpoints.blockchain_rest_api)
Agreed. Renamed in b3ea6058e1.

2025-01-03 13:51 UTC, Dentosal commented on crates/services/shared-sequencer/src/service.rs
> +    async fn blobs(&mut self) -> anyhow::Result<Option<SSBlobs>> {
Refactored in b3ea6058e1

2025-01-03 13:51 UTC, Dentosal commented on crates/services/shared-sequencer/src/service.rs
> +                if let Some(blobs) = blobs {
b3ea6058e1

2025-01-03 13:51 UTC, Dentosal commented on crates/services/shared-sequencer/src/lib.rs
> +        // We want to estimate the transaction to know hat amount and fee to use.
b3ea6058e1

2025-01-03 14:28 UTC, acerone85 submitted a review, later dismissed

2025-01-03 15:09 UTC, rafal-ch commented on crates/services/shared-sequencer/src/service.rs
> +                let next_order = self.prev_order.map(|prev| prev.wrapping_add(1)).unwrap_or(0);
It seems that `ensure_prev_order` doesn't really ensure that we have the "prev_order", because the `http_api::get_topic` can still return `None`.

It's probably fine to start at `0` in this case, but I'm just leaving the comment for others to double-check :)

2025-01-03 15:13 UTC, rafal-ch commented on crates/services/shared-sequencer/src/service.rs
> +                tracing::info!("Posted block to shared sequencer {blobs:?}");
How many blobs we can potentially have in the collection? Asking because we may risk clogging the log with super long messages on `info` level. Maybe logging the `.len()` would suffice? Or something like range: "blobs.first().height, blobs.last().height"?

2025-01-03 15:31 UTC, rafal-ch commented on crates/services/shared-sequencer/src/lib.rs
> +            latest_height.saturating_add(64),
Do we know at what pace the sequencer chain produces blocks?

2025-01-03 15:39 UTC, rafal-ch commented on crates/services/shared-sequencer/src/lib.rs
> +        signature_bytes[32] &= 0x7f;
A nit: It could be a little bit more clear if we have the `fn non_normalized()` added to `impl Signature`.

2025-01-03 15:56 UTC, rafal-ch commented on crates/services/shared-sequencer/src/lib.rs
> +        let gas_price = gas_price.saturating_add(1);
Do we have a rationale for this piece of code. I was wondering:
1. why we truncate? (and how can we be sure that _dot_ will be used as decimal separator)?
2. why we ceil to the next integer?

2025-01-06 00:14 UTC, xgreenx commented on crates/services/shared-sequencer/src/service.rs
> +        let shared_sequencer_client = if let Some(endpoints) = &self.config.endpoints {
We want to connect to SS network, to get the initial information about it(and verify that we can connect to it), but maybe posting right now is not available because of empty balance, or maybe we want to check that URL are valid but do posting from another node. Many reasons from the deployment perspective.

2025-01-06 00:15 UTC, xgreenx commented on crates/services/shared-sequencer/src/service.rs
> +                let next_order = self.prev_order.map(|prev| prev.wrapping_add(1)).unwrap_or(0);
If we use 0 when it shouldn't be zero, SS will return an error and we will re-fetch the `pred_order`

2025-01-06 01:23 UTC, Dentosal commented on crates/services/shared-sequencer/src/lib.rs
> +            latest_height.saturating_add(64),
Once per second, IIRC

2025-01-06 01:24 UTC, Dentosal commented on crates/services/shared-sequencer/src/lib.rs
> +        signature_bytes[32] &= 0x7f;
Yep. This has to be done in  `fuel-vm`, though. I'll open an issue: https://github.com/FuelLabs/fuel-vm/issues/886

2025-01-06 01:26 UTC, Dentosal commented on crates/services/shared-sequencer/src/lib.rs
> +        let gas_price = gas_price.saturating_add(1);
We need an integer for this. Yep, dot is the separator here. Ceil makes sure that the number is always at least large enough.

2025-01-06 01:29 UTC, Dentosal commented on crates/services/shared-sequencer/src/service.rs
> +                tracing::info!("Posted block to shared sequencer {blobs:?}");
My understanding is that the blobs posted here aren't necessarily adjacent, so logging only len or first and last isn't sufficient. In any case `SSBlob` is quite small.

```rust
pub struct SSBlob {
    block_height: BlockHeight,
    block_id: BlockId,
}
```

2025-01-06 08:57 UTC, AurelienFT approved these changes

2025-01-06 08:58 UTC, AurelienFT requested changes

2025-01-06 08:58 UTC, AurelienFT commented on ci_checks.sh
> +cargo nextest run --all-features --workspace &&
Huh I think you changed an other line instead of removing this change.

2025-01-06 09:21 UTC, Dentosal commented on ci_checks.sh
> +cargo nextest run --all-features --workspace &&
Not sure what happeded here. Well, now I forced the file to match latest `master` in a0f34f68f6

2025-01-06 15:23 UTC, AurelienFT approved these changes

2025-01-07 02:24 UTC, xgreenx commented on crates/services/shared-sequencer/src/lib.rs
> +            latest_height.saturating_add(64),
SS network produces block each 6 seconds

2025-01-07 02:26 UTC, xgreenx approved these changes

2025-01-07 09:06 UTC, AurelienFT approved these changes

2025-01-08 18:25 UTC, merged