Add the algorithm code
FuelLabs/fuel-core pull request #1948
Opened 2024-06-07 16:23 UTC by MitchTurner

Part of https://github.com/FuelLabs/fuel-core/issues/1624

[Short description of the changes.]

## Checklist
- [ ] Breaking changes are clearly marked as such in the PR description and changelog
- [ ] New behavior is reflected in tests
- [ ] [The specification](https://github.com/FuelLabs/fuel-specs/) matches the implemented behavior (link update PR if changes are needed)

### Before requesting review
- [ ] I have reviewed the code myself
- [ ] I have created follow-up issues caused by this PR and linked them here

### After merging, notify other teams

[Add or remove entries as needed]

- [ ] [Rust SDK](https://github.com/FuelLabs/fuels-rs/)
- [ ] [Sway compiler](https://github.com/FuelLabs/sway/)
- [ ] [Platform documentation](https://github.com/FuelLabs/devrel-requests/issues/new?assignees=&labels=new+request&projects=&template=NEW-REQUEST.yml&title=%5BRequest%5D%3A+) (for out-of-organization contributors, the person merging the PR will do this)
- [ ] Someone else?

2024-06-14 17:56 UTC, MitchTurner commented
It sounds like we aren't planning on having any DA costs in the immediate future. So I think we put a pin in the research for the DA projection stuff and move forward. I could spend weeks on improving DA gas price portion. The Exec Gas Price portion is much simpler and all we need for now.

If we set the costs to 0 in prod, then this algo will work just fine :)

From here we can get the updater and algo installed into our code and we can make adjustments as they come up. The general shape is correct.

2024-06-16 21:50 UTC, MitchTurner commented
Need to disallow unchecked arithmetic.

2024-06-17 17:04 UTC, xgreenx commented on crates/gas-price-algorithm/src/main.rs
> +use plotters::prelude::*;
Maybe we could move it to own binary

2024-06-17 19:25 UTC, MitchTurner commented
Looks like the checked arithmetic broke some things. I'm debugging.

2024-06-18 11:51 UTC, Dentosal commented on crates/gas-price-algorithm/gas-price-analysis/Cargo.toml
> +
```suggestion
```

2024-06-18 16:09 UTC, Dentosal commented on crates/gas-price-algorithm/gas-price-analysis/Cargo.toml
> +
```suggestion
publish = false

```

2024-06-18 16:11 UTC, Dentosal commented on crates/gas-price-algorithm/Cargo.toml
> +name = "gas-price-algorithm"
```suggestion
name = "fuel-gas-price-algorithm"
```

2024-06-18 16:11 UTC, Dentosal commented on Cargo.toml
> +gas-price-algorithm = { version = "0.29.0", path = "./crates/gas-price-algorithm" }
```suggestion
fuel-gas-price-algorithm = { version = "0.29.0", path = "./crates/gas-price-algorithm" }
```

2024-06-18 19:31 UTC, MitchTurner commented
@Dentosal I made some small functional changes wrt minimum gas prices.

2024-06-18 21:29 UTC, MitchTurner commented on crates/fuel-gas-price-algorithm/src/lib.rs
> +/// the cost for that block. Every time the DA recording is updated, that the projections are recalculated.
```suggestion
/// the cost for that block. Every time the DA recording is updated, the projections are recalculated.
```

2024-06-18 21:45 UTC, MitchTurner commented on crates/fuel-gas-price-algorithm/src/lib.rs
> +    /// The gas price for to cover the execution of the next block
```suggestion
    /// The gas price to cover the execution of the next block
```

2024-06-18 22:05 UTC, Dentosal requested changes
Still some change suggestions unapplied

2024-06-18 22:08 UTC, MitchTurner commented on crates/gas-price-algorithm/gas-price-analysis/Cargo.toml
> +
I just removed this.

2024-06-18 22:36 UTC, Dentosal approved these changes

2024-06-19 17:36 UTC, Dentosal approved these changes

2024-06-19 17:36 UTC, merged