Remove Openssl dependency from fuel-client
FuelLabs/fuel-core pull request #219
Opened 2022-03-21 21:24 UTC by ControlCplusControlV

Disables surf's default features (which compiles using openssl-sys) and instead enables rustls as a replacement. From my local testing it seems to have removed the need for openssl from fuel-gql client. But as fuel-gql-client is a dependency of other crates it would need a version bump to fully remove the openssl dependency

Would it then be better to version bump fuel-gql client in this PR, or save that for a full release to fully remove openssl?

2022-03-21 21:24 UTC, ControlCplusControlV commented
Done as part of #133

2022-03-21 21:31 UTC, Voxelot commented
In our release process, we always bump the versions in a separate PR once we're ready to schedule the release. That way we can review all changes accumulated on master and verify the version bump follows semver conventions.

2022-03-21 21:53 UTC, adlerjohn commented on fuel-client/Cargo.toml
> +surf = {version = "2.2",default-features = false ,features = ["h1-client-rustls"] }
```suggestion
surf = { version = "2.2", default-features = false, features = ["h1-client-rustls"] }
```

2022-03-21 21:54 UTC, adlerjohn reviewed
The Cargo lockfile should also be committed, no? I imagine there will be changes, specifically it should no longer have `openssl-sys`.

2022-03-21 22:17 UTC, Voxelot approved these changes

2022-03-21 22:20 UTC, Voxelot commented
[nit] we may be able to remove the openssl installation steps from the repo README.md / CONTRIBUTING.md

2022-03-21 22:31 UTC, ControlCplusControlV commented
Was waiting on a version bump to confirm that before removing that, because openssl-sys is still a dependency of older (latest release) fuel-gql-client versions used by other crates.

2022-03-21 22:32 UTC, Voxelot commented
Makes sense, we can defer that to another PR after this is released.

2022-03-21 22:34 UTC, adlerjohn requested changes
The lockfile doesn't actually seem to have `openssl-sys` removed?

2022-03-21 22:44 UTC, adlerjohn approved these changes
NVM, I see the comment on a circular dependency

2022-03-22 02:21 UTC, Voxelot commented
This circular dep should get resolved when https://github.com/FuelLabs/fuels-rs/issues/62 is finished allowing the indexer to upgrade it's version of fuels-rs.

2022-03-22 02:38 UTC, merged