Capitalize GQL field descriptions
FuelLabs/fuel-core pull request #256
Opened 2022-04-03 18:41 UTC by ControlCplusControlV

Done to fix #123  , I believe I regenerated the `schema.sdl` correctly but not too familiar so let me know if I missed a step. Went looking for fields of error in `fuel-core/schema/*` so its also possible I may have missed other GQL descriptions, I also tried to avoid capitalizing words which reference variables (like `utxo_id`) and instead added prefixes to those to fit in line with the new style while maintaining clarity.

2022-04-03 21:51 UTC, AlicanC requested changes

2022-04-03 21:51 UTC, AlicanC commented on fuel-core/src/schema/block.rs
> +        #[graphql(desc = "Id of the block")] id: Option<BlockId>,
Replace `Id` with `ID` because here it's just an English abbreviation.

2022-04-03 21:51 UTC, AlicanC commented on fuel-core/src/schema/tx.rs
> +        #[graphql(desc = "The id of the transaction")] id: TransactionId,
s/id/ID

2022-04-03 21:51 UTC, AlicanC commented on fuel-core/src/schema/coin.rs
> +        #[graphql(desc = "The utxo_id of the coin")] utxo_id: UtxoId,
Replace `utxo_id` with `ID`.

2022-04-04 07:29 UTC, AlicanC approved these changes
👍

2022-04-04 16:05 UTC, Voxelot approved these changes

2022-04-04 21:28 UTC, merged