Use `tokio::main` for `fuel-gql-client` cli
FuelLabs/fuel-core pull request #811
Opened 2022-12-03 19:01 UTC by xgreenx

2022-12-03 20:23 UTC, ControlCplusControlV requested changes
Tested with some basic commands on `beta-2`
Such as
```sh
./fuel-gql-cli --endpoint http://node-beta-2.fuel.network transaction receipts 0x555c0e13daa880ec4ce315fe38bd86b4f54bbbd4f439451ca772fd89ae17ba68
```
and it returns back results successfully.

Looking at the discussion, it seems `tokio::main` is unavoidable, maybe this can be revisited as we continue to refactor our async code (I know there are a lot of async functions that don't need to be still left) and gql client. This also brings up that I would suggest adding `cli` tests back into the pipeline, because while they do slow down CI, as people start using our cli more and more it provides critical coverage so we know we aren't breaking things (but that is a separate issue).

This is where my suggestions come in though, if we use a single_thread runtime we get async compatibility but can cut out compiling an entire multi-threaded runtime for the client

2022-12-03 20:23 UTC, ControlCplusControlV commented on fuel-client/Cargo.toml
> +tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
```suggestion
tokio = { version = "1.21", features = ["macros"] }
```

2022-12-03 20:23 UTC, ControlCplusControlV commented on fuel-client/src/main.rs
> +#[tokio::main]
```suggestion
#[tokio::main(flavor="current_thread")]
```

2022-12-03 20:30 UTC, ControlCplusControlV commented on fuel-client/src/main.rs
>      futures::executor::block_on(CliArgs::parse().exec());
```suggestion
    CliArgs::parse().exec().await;
```

Is also needed for my changes to work

2022-12-03 21:04 UTC, ControlCplusControlV approved these changes
LGTM, and with these changes adding `tokio` as a dependency should also address @Voxelot 's concerns of weight (although wait to hear back ofc before merging)

2022-12-04 18:21 UTC, Voxelot commented
Yeah my first concern was weight, the other being locked into tokio for sdks/user-facing libraries. Ideally async interfaces would work with whatever async runtime they use in their app. Since there's no great way around the second concern for now, I think this is a practical compromise for now.

2022-12-04 23:45 UTC, xgreenx commented
To reduce the size, added `tokio` only for binary.

2022-12-05 00:21 UTC, ControlCplusControlV approved these changes

2022-12-05 20:07 UTC, Voxelot approved these changes

2022-12-05 21:00 UTC, merged